# code, slug, namn (singular, gemener där det passar), kategori
Y = [
('5321','underskoterska','undersköterska','Vård & omsorg'),
('2512','systemutvecklare','systemutvecklare','IT & teknik'),
('2341','larare','grundskollärare','Utbildning'),
('5223','butikssaljare','butikssäljare','Handel & service'),
('4322','lagerarbetare','lagerarbetare','Transport & lager'),
('9111','stadare','städare','Handel & service'),
('5330','vardbitrade','vårdbiträde','Vård & omsorg'),
('9412','kokbitrade','restaurang- och köksbiträde','Hotell & restaurang'),
('5222','butikssaljare-dagligvaror','butikssäljare i dagligvaruhandeln','Handel & service'),
('5342','boendestodjare','boendestödjare','Vård & omsorg'),
('5311','barnskotare','barnskötare','Utbildning'),
('3322','saljare','företagssäljare','Försäljning & marknad'),
('5343','personlig-assistent','personlig assistent','Vård & omsorg'),
('2422','utredare','utredare','Administration & ekonomi'),
('4119','kontorsassistent','kontorsassistent','Administration & ekonomi'),
('8332','lastbilsforare','lastbilschaufför','Transport & lager'),
('2343','forskollarare','förskollärare','Utbildning'),
('2221','sjukskoterska','sjuksköterska','Vård & omsorg'),
('7223','cnc-operator','CNC-operatör','Industri & produktion'),
('7111','snickare','snickare','Bygg & hantverk'),
('2421','organisationsutvecklare','organisationsutvecklare','Administration & ekonomi'),
('7411','elektriker','elektriker','Bygg & hantverk'),
('5120','kock','kock','Hotell & restaurang'),
('2143','civilingenjor-elektroteknik','civilingenjör inom elektroteknik','IT & teknik'),
('5312','elevassistent','elevassistent','Utbildning'),
('5131','servitor','servitör','Hotell & restaurang'),
('2149','civilingenjor','civilingenjör','IT & teknik'),
('7231','bilmekaniker','bilmekaniker','Industri & produktion'),
('5152','fastighetsskotare','fastighetsskötare','Handel & service'),
('3313','redovisningsekonom','redovisningsekonom','Administration & ekonomi'),
('4111','ekonomiassistent','ekonomiassistent','Administration & ekonomi'),
('1120','vd','VD','Chefer'),
('2511','it-arkitekt','IT-arkitekt','IT & teknik'),
('7233','underhallsmekaniker','underhållsmekaniker','Industri & produktion'),
('2211','lakare','specialistläkare','Vård & omsorg'),
('4222','kundtjanst','kundtjänstmedarbetare','Handel & service'),
('2330','gymnasielarare','gymnasielärare','Utbildning'),
('2431','marknadsforare','marknadsförare','Försäljning & marknad'),
('2661','socionom','socialsekreterare','Socialt arbete'),
('2423','hr-specialist','HR-specialist','Administration & ekonomi'),
('3112','byggingenjor','byggingenjör','Bygg & hantverk'),
('3113','elingenjor','elingenjör','IT & teknik'),
('3114','maskiningenjor','maskiningenjör','IT & teknik'),
('8331','busschauffor','busschaufför','Transport & lager'),
('3323','inkopare','inköpare','Försäljning & marknad'),
('2144','civilingenjor-maskinteknik','civilingenjör inom maskinteknik','IT & teknik'),
('3312','banktjansteman','banktjänsteman','Administration & ekonomi'),
('2432','kommunikator','kommunikatör','Försäljning & marknad'),
('2412','controller','controller','Administration & ekonomi'),
('5413','sakerhetsvakt','väktare','Säkerhet'),
('3360','polis','polis','Säkerhet'),
('8342','anlaggningsmaskinforare','anläggningsmaskinförare','Bygg & hantverk'),
('3324','ordersamordnare','ordersamordnare','Administration & ekonomi'),
('6113','tradgardsanlaggare','trädgårdsanläggare','Bygg & hantverk'),
('1251','forsaljningschef','försäljningschef','Chefer'),
('4117','medicinsk-sekreterare','medicinsk sekreterare','Vård & omsorg'),
('5341','skotare','skötare','Vård & omsorg'),
('2342','fritidspedagog','fritidspedagog','Utbildning'),
('7114','anlaggningsarbetare','anläggningsarbetare','Bygg & hantverk'),
('3422','idrottstranare','idrottstränare','Socialt arbete'),
('3411','behandlingsassistent','behandlingsassistent','Socialt arbete'),
('3121','arbetsledare-bygg','arbetsledare inom bygg','Bygg & hantverk'),
('3512','it-tekniker','IT-tekniker','IT & teknik'),
('2351','specialpedagog','specialpedagog','Utbildning'),
('3423','fritidsledare','fritidsledare','Socialt arbete'),
('4112','loneadministrator','löneadministratör','Administration & ekonomi'),
('2142','civilingenjor-bygg','civilingenjör inom bygg och anläggning','Bygg & hantverk'),
('3511','drifttekniker-it','drifttekniker inom IT','IT & teknik'),
('2411','revisor','revisor','Administration & ekonomi'),
('2272','fysioterapeut','fysioterapeut (sjukgymnast)','Vård & omsorg'),
('1212','ekonomichef','ekonomichef','Chefer'),
('4224','hotellreceptionist','hotellreceptionist','Hotell & restaurang'),
('2312','universitetslektor','universitetslektor','Utbildning'),
('1412','rektor','rektor','Chefer'),
('2241','psykolog','psykolog','Vård & omsorg'),
('7113','betongarbetare','betongarbetare','Bygg & hantverk'),
('3321','forsakringsradgivare','försäkringsrådgivare','Försäljning & marknad'),
('5350','tandskoterska','tandsköterska','Vård & omsorg'),
('5412','kriminalvardare','kriminalvårdare','Säkerhet'),
('2419','ekonom','ekonom','Administration & ekonomi'),
('2662','kurator','kurator','Socialt arbete'),
('4420','brevbarare','brevbärare','Transport & lager'),
('2413','finansanalytiker','finansanalytiker','Administration & ekonomi'),
('8344','truckforare','truckförare','Transport & lager'),
('7212','svetsare','svetsare','Industri & produktion'),
('1312','it-chef','IT-chef','Chefer'),
('2212','st-lakare','ST-läkare','Vård & omsorg'),
('2642','journalist','journalist','Försäljning & marknad'),
('2611','advokat','advokat','Juridik'),
('2619','jurist','jurist','Juridik'),
('2614','bolagsjurist','bolagsjurist','Juridik'),
('2260','tandlakare','tandläkare','Vård & omsorg'),
('5411','brandman','brandman','Säkerhet'),
('5141','frisor','frisör','Handel & service'),
('7119','byggnadsarbetare','byggnadsarbetare','Bygg & hantverk'),
('2250','veterinar','veterinär','Vård & omsorg'),
('2222','barnmorska','barnmorska','Vård & omsorg'),
('2273','arbetsterapeut','arbetsterapeut','Vård & omsorg'),
('3334','fastighetsmaklare','fastighetsmäklare','Försäljning & marknad'),
('8311','lokforare','lokförare','Transport & lager'),
('7125','vvs-montor','VVS-montör','Bygg & hantverk'),
('7131','malare','målare','Bygg & hantverk'),
('2161','arkitekt','arkitekt','Bygg & hantverk'),
('3153','pilot','pilot','Transport & lager'),
('2516','it-sakerhetsspecialist','IT-säkerhetsspecialist','IT & teknik'),
]
